version: "3"
services:

  web:
    container_name: w3development_php
    build: ./environments/docker/webservice/php7.2/
    image: w3development/php:7.2-apache
    ports:
      - "80"
      - "443"
    volumes:
      - ./:/var/www/html
      - ./environments/docker/webservice/vhosts:/etc/apache2/sites-enabled
      - ./environments/docker/webservice/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      w3development_nat:
        ipv4_address: 172.0.1.30
    links:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  phpmyadmin:
    container_name: w3development_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: 172.0.1.10
      PMA_PORT: 3306     
    ports:
      - '80'
    volumes: 
      - /sessions
    networks:
      w3development_nat:
        ipv4_address: 172.0.1.20

  db:
    container_name: w3development_db
    build: ./environments/docker/database/mysql5.7/
    image: w3development/db:5.7-mysql
    ports:
      - "3306"
    volumes:
    - ./data/dump/database.sql:/docker-entrypoint-initdb.d/database.sql
    - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=w3development
      - MYSQL_USER=w3development
      - MYSQL_PASSWORD=pass
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 1G
        reservations:
          cpus: '0.0001'
          memory: 512M
    networks:
      w3development_nat:
        ipv4_address: 172.0.1.10

networks:
    w3development_nat:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
            - subnet: 172.0.1.0/24

volumes:
  w3development_php_data:
  w3development_db_data: