version: "3"
services:
  db:
    image: mysql:5.7
    container_name: w3development-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3pass
    ports:
    - "33061:3306"
    volumes:
       - ./docker/db/init/database.sql:/docker-entrypoint-initdb.d/database.sql
       - ./docker/db/mysql:/var/lib/mysql
  web:
    image: w3development:php7.4
    container_name: w3development-web
    build: ./docker/web
    ports:
      - "8081:80"
      - "44301:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - ./docker/web/etc/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/etc/vhosts:/etc/apache2/sites-enabled
    links:
      - db

networks:
  default:
      name: w3development_network
      driver: bridge
