version: "3"
services:
  db:
    image: mysql:5.7
    container_name: w3development-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joh316
      MYSQL_DATABASE: typo3
      MYSQL_USER: w3dev
      MYSQL_PASSWORD: w3pass
    ports:
    - "33061:3306"
    volumes:
      - db-data
  web:
    image: w3development:php7.4
    container_name: w3development-web
    build: ./docker/service/web
    ports:
      - "8081:80"
      - "4431:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
      - ./docker/service/web/etc/php.ini:/usr/local/etc/php/php.ini
      - ./docker/service/web/etc/vhosts:/etc/apache2/sites-enabled
    links:
      - db

networks:
  default:
      name: w3development_network
      driver: bridge

volumes:
  db-data:
