<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'FluidTYPO3\\Flux\\' => array($typo3InstallDir . 'typo3conf/ext/flux/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'HTML\\Sourceopt\\' => array($typo3InstallDir . 'typo3conf/ext/sourceopt/Classes'),
    'In2code\\Powermail\\' => array($typo3InstallDir . 'typo3conf/ext/powermail/Classes'),
    'In2code\\Powermailrecaptcha\\' => array($typo3InstallDir . 'typo3conf/ext/powermailrecaptcha/Classes'),
    'T3G\\AgencyPack\\Blog\\' => array($typo3InstallDir . 'typo3conf/ext/blog/Classes'),
    'W3Development\\Theme\\' => array($typo3InstallDir . 'typo3conf/ext/theme/Classes'),
);
