name: w3development
type: typo3
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "8086"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - TYPO3_CONTEXT=Development
nodejs_version: "20"